# Generated by Django 5.1.2 on 2024-11-14 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prodect',
            new_name='Product',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='prodect_image',
            new_name='product_image',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='tage',
            new_name='tag',
        ),
    ]
