# Generated by Django 5.1.2 on 2024-12-08 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Out for shipping', 'Out for shipping'), ('Pending', 'Pending')], default='Pending', max_length=150),
        ),
    ]
